project:
  type: website
  output-dir: docs

website:
  title: "Job Trends 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: job-trends-2024.qmd
        text: Job Trends 2024
      - href: data_analysis.qmd
        text: Data Analysis

format:
  html:
    theme: cosmo
    toc: true

